Sub 操作工作表()

'    Worksheets("工作表1").Copy after:=Worksheets("工作表2")
'    ActiveSheet.name = "工作表1複製"
    'Worksheets("工作表1").Copy before:=Worksheets("工作表2")
    'ActiveSheet.name = "工作表1複製"
'    Worksheets("工作表1").Copy
'    ActiveSheet.name = "工作表1複製"
'    Worksheets("工作表1").Move
'    ActiveSheet.name = "工作表1移動"
'    Worksheets("工作表1").Move before:=Worksheets("工作表1複製")
'    ActiveSheet.name = "工作表1移動"
'    Worksheets("工作表6").Delete '刪除工作表並會警告
'    Application.DisplayAlerts = False   '刪除工作表並不會警告
'    Worksheets("工作表6").Delete        '注意此種用法會取小所有警告, 使用後必須開啟
'    Application.DisplayAlerts = True    '記得回復alert
    
'End Sub